services:
  backend:
    image: bogdanmehedin/springboot-encoder-app:latest
    container_name: springboot-encoder-app
    ports:
      - "8080:8080"

  frontend:
    image: bogdanmehedin/angular-encoder-app:latest
    container_name: angular-encoder-app
    ports:
      - "80:80"
